In [1]:
import numpy as np

In [2]:
lista = [123,45,53,4,11,3,-7,33]
tablica = np.array([123,45,53,4,11,3,-7,33])

print(lista)
print(tablica)
print(type(lista))
print(type(tablica))

[123, 45, 53, 4, 11, 3, -7, 33]
[123  45  53   4  11   3  -7  33]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(lista *2)
print(tablica * 2)

[123, 45, 53, 4, 11, 3, -7, 33, 123, 45, 53, 4, 11, 3, -7, 33]
[246  90 106   8  22   6 -14  66]


In [ ]:
print(len(lista))
print(tablica.shape)

print([[10,20],[30,40]])
array2D = np.array([[10,20,30],[30,40,40]])
array2D.shape

8
(8,)
[[10, 20], [30, 40]]


(2, 3)

In [11]:
tablica > 0

array([ True,  True,  True,  True,  True,  True, False,  True])

In [15]:
tablica[2:4]

array([53,  4])

In [12]:
tablica[tablica > 0]

array([123,  45,  53,   4,  11,   3,  33])

In [13]:
tablica

array([123,  45,  53,   4,  11,   3,  -7,  33])

In [14]:
tablica = tablica[tablica>0]
tablica

array([123,  45,  53,   4,  11,   3,  33])