In [64]:
import numpy as np

In [65]:
lista = [123,45,53,4,11,3,-7,33]
tablica = np.array([123,45,53,4,11,3,-7,33])

print(lista)
print(tablica)
print(type(lista))
print(type(tablica))

[123, 45, 53, 4, 11, 3, -7, 33]
[123  45  53   4  11   3  -7  33]
<class 'list'>
<class 'numpy.ndarray'>


In [66]:
# lista powiela elementy(rośnie) a tablica wykonuje operacje na każdej wartości modyfikując ją
print(lista *2)
print(tablica * 2)

[123, 45, 53, 4, 11, 3, -7, 33, 123, 45, 53, 4, 11, 3, -7, 33]
[246  90 106   8  22   6 -14  66]


In [67]:
print(len(lista))
print(tablica.shape)

print([[10,20],[30,40]])
array2D = np.array([[10,20,30],[30,40,40]])
array2D.shape

8
(8,)
[[10, 20], [30, 40]]


(2, 3)

In [68]:
tablica > 0

array([ True,  True,  True,  True,  True,  True, False,  True])

In [69]:
tablica[2:4]

array([53,  4])

In [70]:
tablica[tablica > 0]

array([123,  45,  53,   4,  11,   3,  33])

In [71]:
tablica

array([123,  45,  53,   4,  11,   3,  -7,  33])

In [72]:
tablica = tablica[tablica>0]
tablica

array([123,  45,  53,   4,  11,   3,  33])

In [73]:
#array2D = np.array([[10,20,30],[30,40,40]])
array2D[:,1]

array([20, 40])

In [74]:
tablica

array([123,  45,  53,   4,  11,   3,  33])

In [75]:
tablica2 = tablica[:3]

In [76]:
tablica2[0] = 7
tablica2

array([ 7, 45, 53])

In [77]:
tablica

array([ 7, 45, 53,  4, 11,  3, 33])

In [78]:
#aby nie dostawać widoku na część danych ale realną kopię, która możemy edytować osobno : copy()
tablica2 = tablica[:3].copy()

In [79]:
tablica = np.append(tablica,tablica)
tablica = np.append(tablica,np.array([-2,-3]))

tablica

array([ 7, 45, 53,  4, 11,  3, 33,  7, 45, 53,  4, 11,  3, 33, -2, -3])

In [80]:
print(tablica.mean())
print(tablica.max())
print(tablica.min())
print(tablica.std())
print(np.abs(tablica))

19.1875
53
-3
19.934952815344207
[ 7 45 53  4 11  3 33  7 45 53  4 11  3 33  2  3]
