2.1 Zdefiniuj tablicę NumPy z sześcioma pomiarami tętna z opaski klienta po treningu, np.:
 65, 72, 80, 78, 90, 85
 Napisz program, który obliczy średnie tętno, minimalne oraz maksymalne tętno, wydrukuje w konsoli tylko te wartości tętna, które są wyższe od średniej oraz przygotuje nową tablicę, w której każde tętno jest zmniejszone o 5 (symulacja poprawy kondycji po kilku tygodniach treningu).

In [8]:
import numpy as np

array = np.array([65, 72, 80, 78, 90, 85])
mean = array.mean()
mean

np.float64(78.33333333333333)

In [9]:
print(array.max())
print(array.min())

90
65


In [10]:
array[array > mean]

array([80, 90, 85])

In [11]:
array - 5

array([60, 67, 75, 73, 85, 80])

In [12]:
array

array([65, 72, 80, 78, 90, 85])